name: amma_foodcity
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Storage and Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0

  # UI Components
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.6.0
  shimmer: ^3.0.0
  dots_indicator: ^3.0.0

  # Networking and API
  graphql_flutter: ^5.1.2
  http: ^1.1.2
  url_launcher: ^6.2.1
  shopify_flutter: ^1.0.0

  # Utils and Helpers
  package_info_plus: ^5.0.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  hive_generator: ^2.0.1

  # Linting
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/products/
    - assets/images/